### PR TITLE
Add gitarchive files

### PR DESCRIPTION
**Pull request by jeanconn**
Add gitarchive files

### CODE REVIEW

**Comment by jeanconn** [comment]
@javierggt I'm not sure how to test this.

**Comment by taldcroft** [comment]
The file content looks fine to me.  The original testing of the concept was long ago.

**Comment by taldcroft** [comment]
As a reminder, this follows the recipe documented at https://pypi.org/project/setuptools-scm-git-archive.  It worked as advertised when I tested it.

**Comment by jeanconn** [comment]
OK.

**Comment by javierggt** [comment]
Now I saw this. If this file was missing, I wonder if one also needs .gitattributes: https://pypi.org/project/setuptools-scm-git-archive/

**Comment by javierggt** [comment]
I added the file to the same branch.

**Comment by jeanconn** [comment]
Huh.  I had copied them both but it does look like I lost one along the way.  I'm not sure how adding the file to the same branch helps, as I'd merged and deleted this PR.    You can push to master and I'll tag a new find_attitude.

**Pull request merged**
