### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by taldcroft**
This is passing tests in Ska and Ska3 on HEAD linux.

~~One concern is in the details of finding the solution, where it appears that different numbers of matching edges are found in Py2 vs Py3.~~ [EDIT: the test has a random component, so that was the reason).

One does see diffs like the order of the cliques that are reported (see below), but these are inconsequential.

**Py3**
```
test_find_attitude.py::test_get_stars_from_greta 2018-07-25 11:47:13,857 Using AGASC pairs file /proj/sot/ska/data/find_attitude/distances.h5
2018-07-25 11:47:13,870 Starting get_match_graph
2018-07-25 11:47:13,870 Getting matches from file
2018-07-25 11:47:15,238 Adding edges from 652365 matching distance pairs
2018-07-25 11:47:26,478 Added total of 182353 nodes
2018-07-25 11:47:26,492 Getting all triangles from match graph
2018-07-25 11:47:27,925 Finding triangles that match stars pattern
2018-07-25 11:47:28,107 Checking clique [260186640, 189142952, 189143696, 189148400, 189148592]
```

**Py2**
```
test_find_attitude.py::test_get_stars_from_greta 2018-07-25 11:47:44,831 Using AGASC pairs file /proj/sot/ska/data/find_attitude/distances.h5
2018-07-25 11:47:44,841 Starting get_match_graph
2018-07-25 11:47:44,841 Getting matches from file
2018-07-25 11:47:45,859 Adding edges from 652365 matching distance pairs
2018-07-25 11:48:03,199 Added total of 182353 nodes
2018-07-25 11:48:03,211 Getting all triangles from match graph
2018-07-25 11:48:04,818 Finding triangles that match stars pattern
2018-07-25 11:48:04,996 Checking clique [189148592, 189142952, 189143696, 189148400, 260186640]
```

### CODE REVIEW

**Comment by jeanconn** [comment]
Seems maybe worth adding testr before cutting a new version?

**Comment by jeanconn** [comment]
I'm getting  TableReplaceWarning s when I run the tests on Py3.  Do you want to come out ahead of these or do we just not care?
```
find_attitude/tests/test_find_attitude.py::test_overlapping_distances
  /proj/sot/ska/jeanproj/git/find_attitude/find_attitude/tests/test_find_attitude.py:33: TableReplaceWarning: replaced column 'MAG_ACA' which looks like an array slice. The new column no longer shares memory with the original array.
    stars['MAG_ACA'] += stars['MAG_ERROR']
```

**Comment by taldcroft** [comment]
Passing tests (`python setup.py test`) in Ska2 and Ska3 now with no warnings.

**Comment by jeanconn** [comment]
Will we want to update the installed Ska2 version or leave that alone?  Does this need to be tested via the kadi web interface at all before promotion?

**Comment by jeanconn** [comment]
What is status of this one?  I think I was withholding approval with the idea that I wasn't sure if we needed kadi testing before including this in ska3-flight.

**Comment by taldcroft** [comment]
About the Ska2 update, no need.

This does not need kadi testing.  Kadi is currently running Ska2, so there is no interaction.  It would be beneficial to have this in flight Ska3 when we do the migration of kadi to run on Ska3.

**Comment by taldcroft** [comment]
I just gave this a version 3.0.

**Pull request merged**
